"""Component ID/type → KiCad symbol library mapping."""

from __future__ import annotations

from pathlib import Path

from pydantic import BaseModel


class KiCadSymbolRef(BaseModel):
    library: str
    symbol: str


KICAD_SYMBOL_MAP: dict[str, KiCadSymbolRef] = {
    "TPS62933DRLR": KiCadSymbolRef(library="Device", symbol="TPS62933"),
}

KICAD_TYPE_MAP: dict[str, KiCadSymbolRef] = {
    "resistor": KiCadSymbolRef(library="Device", symbol="R"),
    "capacitor": KiCadSymbolRef(library="Device", symbol="C"),
    "inductor": KiCadSymbolRef(library="Device", symbol="L"),
    "diode": KiCadSymbolRef(library="Device", symbol="D"),
    "led": KiCadSymbolRef(library="Device", symbol="LED"),
    "transistor": KiCadSymbolRef(library="Device", symbol="Q_NPN_BCE"),
    "mosfet": KiCadSymbolRef(library="Device", symbol="Q_NMOS_GSD"),
    "crystal": KiCadSymbolRef(library="Device", symbol="Crystal"),
    "connector": KiCadSymbolRef(library="Connector", symbol="Conn_01x02"),
}

_GENERATED_SYMBOL_MAP: dict[str, KiCadSymbolRef] | None = None


def _load_generated_symbol_map() -> dict[str, KiCadSymbolRef]:
    """
    Load symbol_map.json generated by Tier 0 batch runner.
    Returns empty dict if file does not exist (not an error — Tier 0 may not
    have run yet).
    Result is cached in module-level _GENERATED_SYMBOL_MAP after first load.
    """
    global _GENERATED_SYMBOL_MAP
    if _GENERATED_SYMBOL_MAP is not None:
        return _GENERATED_SYMBOL_MAP
    map_path = Path("data/kicad_maps/symbol_map.json")
    if not map_path.exists():
        _GENERATED_SYMBOL_MAP = {}
        return _GENERATED_SYMBOL_MAP
    import json

    with open(map_path, encoding="utf-8") as f:
        raw = json.load(f)
    _GENERATED_SYMBOL_MAP = {
        k: KiCadSymbolRef(library=v["library"], symbol=v["symbol"])
        for k, v in raw.items()
    }
    return _GENERATED_SYMBOL_MAP


def resolve_kicad_symbol_by_name(symbol_name: str) -> KiCadSymbolRef | None:
    """
    Look up a KiCad symbol by its bare symbol name (e.g. "OPA189").
    Uses the Tier 0 generated map. Returns None if not found.
    Does not fall back to KICAD_SYMBOL_MAP or KICAD_TYPE_MAP.
    """
    generated = _load_generated_symbol_map()
    return generated.get(symbol_name)


def resolve_kicad_symbol(
    component_id: str,
    component_type: str,
) -> KiCadSymbolRef:
    generated = _load_generated_symbol_map()
    if component_id in generated:
        return generated[component_id]
    if component_id in KICAD_SYMBOL_MAP:
        return KICAD_SYMBOL_MAP[component_id]
    if component_type in KICAD_TYPE_MAP:
        return KICAD_TYPE_MAP[component_type]
    return KiCadSymbolRef(library="Device", symbol="IC")
